name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "AKIAYSE4N6J2TGAIM3QR"  # Hardcoded AWS Access Key ID
        aws-secret-access-key: "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"  # Hardcoded AWS Secret Access Key
        aws-region: "ap-south-1"  # Hardcoded AWS Region (Asia Pacific - Mumbai)

    - name: Install Elastic Beanstalk CLI (eb)
      run: |
        # Install the Elastic Beanstalk CLI
        pip install awsebcli

    - name: Deploy to Elastic Beanstalk
      run: |
        # Package the app for Elastic Beanstalk
        zip -r flask-app.zip .
        
        # Use AWS EB CLI to deploy to Elastic Beanstalk
        eb init -p python-3.7 flask-app --region "ap-south-1"  # Specify the region directly
        eb deploy

    - name: Output URL (for tracking)
      id: deploy
      run: |
        # Fetch the Elastic Beanstalk URL dynamically
        EB_URL=$(aws elasticbeanstalk describe-environments --environment-names flask-app-env --query 'Environments[0].CNAME' --output text)
        echo "URL: https://$EB_URL"
